model_type: 'Vanilla' # 'Vanilla'

models:
  KAN:
    module_path: 'models.KAN_CNN'
    type: 'KANCNN'
    activation_class: 'LearnableActivationSigmoid'
  Vanilla:
    module_path: 'models.VanillaCNN'
    type: 'VanillaCNN'

training:
  learning_rate: 0.001
  batch_size: 64
  epochs: 15

  optimizer:
    type: 'Adam'
    parameters:
      lr: 0.001
      # momentum: 0.9 (Adam doesn't use momentum! It uses beta1 & beta2 instead)

  criterion:
    type: 'CrossEntropyLoss'

results:
  name: 'experiment_2'
