model:
  Type: 'CNN'
  module_path: 'CNN'
  input_size: [3, 84, 84]
  num_classes: 100
  
training:
  learning_rate: 0.001
  batch_size: 64
  epochs: 10
  
  criterion:
    type: 'CrossEntropyLoss'
  
  optimizer:
    type: 'Adam'
    parameters:
      lr: 0.001

results:
  name: 'experiment 1'